### ISSUE TITLE
大佬你好！

### ISSUE THREAD

**Issue by YanChao-student** [cforth/MP3Player#3]
我这几天在学习如何制作一个用pyhton写的图形化音乐播放器，今天下载了你的代码，然后运行起来了。遇到的问题是，我点击左上角的**载入文件按钮**，总是找不到符合条件的资源(**明明有MP3文件存在的**)，请问这是怎么回事啊？

**Comment by cforth** [comment]
我其实只做了加载文件夹的功能。。。你可以自己写个加载文件的按钮。。。不过代码需要更改的地方比较多。。。
